@url_dev=http://localhost:3000/api/v1
### signup
POST {{url_dev}}/user/signup
Content-Type: application/json

{
  "username": "toilahuong",
  "email": "toilahuong@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

### login
POST {{url_dev}}/user/login
Content-Type: application/json

{
  "account": "toilahuong",
  "password": "123456"
}

### checklogin
GET {{url_dev}}/user/check-auth
X-Client-ID: 642c40f32ee63685dba73c82
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJjNDBmMzJlZTYzNjg1ZGJhNzNjODIiLCJ1c2VybmFtZSI6IkY0RG5vRDRiWWwiLCJpYXQiOjE2ODA2MjE4MTIsImV4cCI6MTY4MDc5NDYxMn0.k5kDjb9Su2NLRAqaSTXBBPf61nFZabkE1vRHjdXgr1ScnnHGPG6XKrro60Y2E1P4p0ZPvMoxbgw4JUELqcAanDe23WHERWmrsLgkNCezKxSZ9N25BuMAngWMHJA8V_P8gTsZ2h_GhO0x7xWjGU3qHSy46WkBZRzyxIEbsB7fWyOjz30u4S3WBQFuXiz0MrYia0zQBt0Ugm_SXl_WOk9wrqs1jFvcRfyFXb8Q6np5CKVbfPEiAcVxVthUDmorNHFd8ZvUCYxMpSqSRNLQctp184T1ucHbrlIZZU7foiYFHs-IxvDxlSM_rE12dZv0C2bOcrgM_lPLH51c0owEwpx8-mLX4coiQi2MApfu5jOPR6KR3L6OdxVfbrjMIEnktA3_J_I1bzlryoPMacKvpKiwDp81pAKknSmb_e1UbGFwx2oFb23XqTdGgAEH3hnjWTsvgXfTyKwDlhA0W4qtt20bMx7yVwEMUDW5vLdImSWPabe-DVsz62AKDLBOqEDpdb-kFKpB2tn7nvFiZXuYIm7fDLuRfSzu9BX8xMJgWx4Ptp_7WrjPEIblmnSqZqGafqDqcWj1QlE1GfbiWalEWmHEXINl0GHfNz4mIh1tqIR-YrArUYC71faW3Z8XTVpZmwFvGaDMd6D6L4Q4o0dqIEBmm7h34iaH1xyW1mjR6fhNHvY
