@url_dev=http://localhost:3000/api/v1
### signup
POST {{url_dev}}/auth/signup
Content-Type: application/json

{
  "username": "toilahuong",
  "email": "toilahuong@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

### login
POST {{url_dev}}/auth/login
Content-Type: application/json

{
  "account": "toilahuong",
  "password": "123456"
}

### checklogin
GET {{url_dev}}/auth/check-auth
X-Client-ID: 642c40f32ee63685dba73c82
X-Device-ID: 642c40f42ee63685dba73c85
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJjNDBmMzJlZTYzNjg1ZGJhNzNjODIiLCJ1c2VybmFtZSI6IkY0RG5vRDRiWWwiLCJpYXQiOjE2ODA2MjE4MTIsImV4cCI6MTY4MDc5NDYxMn0.k5kDjb9Su2NLRAqaSTXBBPf61nFZabkE1vRHjdXgr1ScnnHGPG6XKrro60Y2E1P4p0ZPvMoxbgw4JUELqcAanDe23WHERWmrsLgkNCezKxSZ9N25BuMAngWMHJA8V_P8gTsZ2h_GhO0x7xWjGU3qHSy46WkBZRzyxIEbsB7fWyOjz30u4S3WBQFuXiz0MrYia0zQBt0Ugm_SXl_WOk9wrqs1jFvcRfyFXb8Q6np5CKVbfPEiAcVxVthUDmorNHFd8ZvUCYxMpSqSRNLQctp184T1ucHbrlIZZU7foiYFHs-IxvDxlSM_rE12dZv0C2bOcrgM_lPLH51c0owEwpx8-mLX4coiQi2MApfu5jOPR6KR3L6OdxVfbrjMIEnktA3_J_I1bzlryoPMacKvpKiwDp81pAKknSmb_e1UbGFwx2oFb23XqTdGgAEH3hnjWTsvgXfTyKwDlhA0W4qtt20bMx7yVwEMUDW5vLdImSWPabe-DVsz62AKDLBOqEDpdb-kFKpB2tn7nvFiZXuYIm7fDLuRfSzu9BX8xMJgWx4Ptp_7WrjPEIblmnSqZqGafqDqcWj1QlE1GfbiWalEWmHEXINl0GHfNz4mIh1tqIR-YrArUYC71faW3Z8XTVpZmwFvGaDMd6D6L4Q4o0dqIEBmm7h34iaH1xyW1mjR6fhNHvY

### logout
POST {{url_dev}}/auth/logout
X-Client-ID: 642c40f32ee63685dba73c82
X-Device-ID: 642c40f42ee63685dba73c85
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJjNDBmMzJlZTYzNjg1ZGJhNzNjODIiLCJ1c2VybmFtZSI6IkY0RG5vRDRiWWwiLCJpYXQiOjE2ODA2MjE4MTIsImV4cCI6MTY4MDc5NDYxMn0.k5kDjb9Su2NLRAqaSTXBBPf61nFZabkE1vRHjdXgr1ScnnHGPG6XKrro60Y2E1P4p0ZPvMoxbgw4JUELqcAanDe23WHERWmrsLgkNCezKxSZ9N25BuMAngWMHJA8V_P8gTsZ2h_GhO0x7xWjGU3qHSy46WkBZRzyxIEbsB7fWyOjz30u4S3WBQFuXiz0MrYia0zQBt0Ugm_SXl_WOk9wrqs1jFvcRfyFXb8Q6np5CKVbfPEiAcVxVthUDmorNHFd8ZvUCYxMpSqSRNLQctp184T1ucHbrlIZZU7foiYFHs-IxvDxlSM_rE12dZv0C2bOcrgM_lPLH51c0owEwpx8-mLX4coiQi2MApfu5jOPR6KR3L6OdxVfbrjMIEnktA3_J_I1bzlryoPMacKvpKiwDp81pAKknSmb_e1UbGFwx2oFb23XqTdGgAEH3hnjWTsvgXfTyKwDlhA0W4qtt20bMx7yVwEMUDW5vLdImSWPabe-DVsz62AKDLBOqEDpdb-kFKpB2tn7nvFiZXuYIm7fDLuRfSzu9BX8xMJgWx4Ptp_7WrjPEIblmnSqZqGafqDqcWj1QlE1GfbiWalEWmHEXINl0GHfNz4mIh1tqIR-YrArUYC71faW3Z8XTVpZmwFvGaDMd6D6L4Q4o0dqIEBmm7h34iaH1xyW1mjR6fhNHvY

### refresh-token
POST {{url_dev}}/auth/refresh-token
X-Device-ID: 642dac1bff055b16cb7964d7
Refresh-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJkYWMxYmZmMDU1YjE2Y2I3OTY0ZDQiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA3MTQ3NzksImV4cCI6MTY4MDcxNDgzOX0.xbQoXP3SFSaAd74N0D7gUcCFaGd5eQc2YgFw8XkQBO6SmSvpeFbO0Plzozy8muQZnpfzANo1LTxokI48e5cm_2i3v441uxiueqjvpVhhCkb9bVuUlPQTwNjYSNdXjc8PwVd42vbd_Hu0jNmY0felnwjzc1YyiS7BsPUJF0DIhtJE2vB2J4L645IrV1kh-vZ-Oe_28VSmqVn2blZRabpFm4RAkdXEfxOo3dJx7zrIJNsDGzXKeD33WFuK1YA3JyPX9IaW4k_py6EOtetZbmj2Sb6BYuUTMG-tgzMvEuv5Ui-XRxcE_KYogjUnRoJcWisAzkOF3fXyheHx4WnGrXI1Pf0H7-KYptOgbKvNR5KSdC2QREaIl0o_0o0LdTj1zf0WW_t12S2qu_f9c9wpi1Mn4-sEONN8IdANBAUysWcWb7m54EBu2aBKelwAXIzN39NIkOY33yDTmIEAC3JqnDft4tmogbCNLIiGCktu4slCQ2RTYDS3sIs0uIMbSplPhu9N7-zynSYWUUCQCBYO8wtxueDUCEErrFarsZ4kGTXN6ZXby24QTKj15YIn7f4vJgpWUO63lw8jWASmnzBFLad10FjlPnBcK77M0p4M_byLcaWzwdt6KcwOTCIw-YUAZjMYDZ2d3aK_NrcSjmkJN51GXXikB8i0YBLbhihKFyaYjPo
