@url_dev=http://localhost:3000/api/v1/accounts
### signup
POST {{url_dev}}/signup
Content-Type: application/json

{
  "username": "toilahuong",
  "email": "toilahuong@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

### login
POST {{url_dev}}/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}

### checklogin
GET {{url_dev}}/check-auth
X-Client-ID: 642f0a7ba0dbd1292f01a73b
X-Device-ID: 642f0a7ca0dbd1292f01a73e
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmMGE3YmEwZGJkMTI5MmYwMWE3M2IiLCJ1c2VybmFtZSI6Ik1KUnRDckZOMlMiLCJpYXQiOjE2ODA4MDQ0NzYsImV4cCI6MTY4MDgwODA3Nn0.VaAWXZ_seX_3Srgja857se0R3wmzT55lR_pX_v_vJQAbVUfD_1eWp4rVUxNo36CfCh-33QhrGLIs0GEARL63J6yxjP1nvLDi8xG5jo9KliS29vNSWkCAzG2ihj2QaLrx60GENt0KyJQ9Zm4EyICSrWzdSuaghdFI6fLKsyNcgm_CMkX5vFuz76OuqZIm3IXAUvisxqOHkWaAPfK6EuOeIyV0W_FDN79Vq7W9q902p1FkSV_-bwy9lylHpGA7i1bFBL3QCA8vVQH68Noew4P936J93bWWuV1hNLaoCG3CexjptLKtU2ZLW22SWPeQU2aRIzWHvqpeyB_PNxvYvMQ10e2D21v82oiMkrEqU1Amr09muhj79jBSbQLq6Iamyjj5Xi8gi1QL6MxOrUx9rxoimNGOsv6tplaaYmgGxezdAggcDK28bG-CkLH_ysIPHg1cCK1VkAXekojRhQ3I0WcnYDEj4SyHT3Zhs8mx4-x_2RDRzXqJ60h6lZhAelXwIqEHJGl5f_jeR13SNdDDbf8a63eSFCGwBEKDYZQFEE2PisJcrhSKeCVnLhLl8y4HaqoiQrxjseBG5jCICbA9xbWyU5UgicGcoUryCL6SFPysRnRxYiePNsFacGRpLT6KsaWY_EYGgf-mxsVRCGpCRz9hF4OyotWUbAq5YEeQD75XYEM

### logout
POST {{url_dev}}/logout
X-Client-ID: 642c40f32ee63685dba73c82
X-Device-ID: 642c40f42ee63685dba73c85
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJjNDBmMzJlZTYzNjg1ZGJhNzNjODIiLCJ1c2VybmFtZSI6IkY0RG5vRDRiWWwiLCJpYXQiOjE2ODA2MjE4MTIsImV4cCI6MTY4MDc5NDYxMn0.k5kDjb9Su2NLRAqaSTXBBPf61nFZabkE1vRHjdXgr1ScnnHGPG6XKrro60Y2E1P4p0ZPvMoxbgw4JUELqcAanDe23WHERWmrsLgkNCezKxSZ9N25BuMAngWMHJA8V_P8gTsZ2h_GhO0x7xWjGU3qHSy46WkBZRzyxIEbsB7fWyOjz30u4S3WBQFuXiz0MrYia0zQBt0Ugm_SXl_WOk9wrqs1jFvcRfyFXb8Q6np5CKVbfPEiAcVxVthUDmorNHFd8ZvUCYxMpSqSRNLQctp184T1ucHbrlIZZU7foiYFHs-IxvDxlSM_rE12dZv0C2bOcrgM_lPLH51c0owEwpx8-mLX4coiQi2MApfu5jOPR6KR3L6OdxVfbrjMIEnktA3_J_I1bzlryoPMacKvpKiwDp81pAKknSmb_e1UbGFwx2oFb23XqTdGgAEH3hnjWTsvgXfTyKwDlhA0W4qtt20bMx7yVwEMUDW5vLdImSWPabe-DVsz62AKDLBOqEDpdb-kFKpB2tn7nvFiZXuYIm7fDLuRfSzu9BX8xMJgWx4Ptp_7WrjPEIblmnSqZqGafqDqcWj1QlE1GfbiWalEWmHEXINl0GHfNz4mIh1tqIR-YrArUYC71faW3Z8XTVpZmwFvGaDMd6D6L4Q4o0dqIEBmm7h34iaH1xyW1mjR6fhNHvY

### refresh-token
POST {{url_dev}}/refresh-token
X-Client-ID: 642c40f32ee63685dba73c82
X-Device-ID: 642dac1bff055b16cb7964d7
Refresh-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJkYWMxYmZmMDU1YjE2Y2I3OTY0ZDQiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA3MTQ3NzksImV4cCI6MTY4MDcxNDgzOX0.xbQoXP3SFSaAd74N0D7gUcCFaGd5eQc2YgFw8XkQBO6SmSvpeFbO0Plzozy8muQZnpfzANo1LTxokI48e5cm_2i3v441uxiueqjvpVhhCkb9bVuUlPQTwNjYSNdXjc8PwVd42vbd_Hu0jNmY0felnwjzc1YyiS7BsPUJF0DIhtJE2vB2J4L645IrV1kh-vZ-Oe_28VSmqVn2blZRabpFm4RAkdXEfxOo3dJx7zrIJNsDGzXKeD33WFuK1YA3JyPX9IaW4k_py6EOtetZbmj2Sb6BYuUTMG-tgzMvEuv5Ui-XRxcE_KYogjUnRoJcWisAzkOF3fXyheHx4WnGrXI1Pf0H7-KYptOgbKvNR5KSdC2QREaIl0o_0o0LdTj1zf0WW_t12S2qu_f9c9wpi1Mn4-sEONN8IdANBAUysWcWb7m54EBu2aBKelwAXIzN39NIkOY33yDTmIEAC3JqnDft4tmogbCNLIiGCktu4slCQ2RTYDS3sIs0uIMbSplPhu9N7-zynSYWUUCQCBYO8wtxueDUCEErrFarsZ4kGTXN6ZXby24QTKj15YIn7f4vJgpWUO63lw8jWASmnzBFLad10FjlPnBcK77M0p4M_byLcaWzwdt6KcwOTCIw-YUAZjMYDZ2d3aK_NrcSjmkJN51GXXikB8i0YBLbhihKFyaYjPo

### change-password
PUT {{url_dev}}/change-password
Content-Type: application/json
X-Client-ID: 642f100f1e6d40dc52e1caf5
X-Device-ID: 642f100f1e6d40dc52e1caf8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmMTAwZjFlNmQ0MGRjNTJlMWNhZjUiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA4MDU5MDMsImV4cCI6MTY4MDgwOTUwM30.N9iyZ2l3srHEK_uoAbOZ-dtjjY9yyfPKaD2PTDiz8r81DBkiEpb7UINDuPrzifrQCdVyIfkLWz6Jf72g5PRZWrw9OEsg9um3l3RoSpVdnzWQmH7ALRSIeWcLoGxTA3vKg9GRRBlef0aZxelVygcJW1-ygwi-NhZLAN2eZlwv4_prnS_6dIix7YkDXAs5Nv1HU_c2vBhxpFU_l7VdablQ3sqgzBVw5uqMXI6wfNi-rZtI6GVTiXIfVHwkHTf0D5nH9wNgIH__4aKpyTYS4X6rQH3C9mwLnmbGi5TaHor7L46QEcccD8F8mI2EREbUYR7wiDD8fwqWO8hZ_jTyqOXU5m4Mn7540VGsmAlE-nx0I75wkxuVRui-wTH0zlh9dpJqqGMmt-Xqa-upOQI686-d39AlxLcnVOdmLWIBJCKoxTp9sQBaiZTMutJHIFnZ1KHjQjxEc0pjHMPsWxm3AmZ3GI__RzlTm38-QuPHD2sYfzzwzi8IC27ceeJxhBRlTCqs1xWR97HSr36NTM_rAL5sbh21K8kTWKodEADrESWwBtFAOvgx0l0dFkzH75a88mzlWNSWrKz8LG8EIrT4COwmohzRPOz6yvUZG3xPlir5lz3YWxHwmzdiP3AvdvDTaUYOHfQY-ZgtKoje147QSjCyF-sZrcfDiEtfmiZ6hfduu90

{
  "oldPassword": "123456",
  "newPassword": "1234567",
  "confirmPassword": "1234567"
}

### change-information
PUT {{url_dev}}/change-information
Content-Type: application/json
X-Client-ID: 642f100f1e6d40dc52e1caf5
X-Device-ID: 642f100f1e6d40dc52e1caf8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmMTAwZjFlNmQ0MGRjNTJlMWNhZjUiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA4MDU5MDMsImV4cCI6MTY4MDgwOTUwM30.N9iyZ2l3srHEK_uoAbOZ-dtjjY9yyfPKaD2PTDiz8r81DBkiEpb7UINDuPrzifrQCdVyIfkLWz6Jf72g5PRZWrw9OEsg9um3l3RoSpVdnzWQmH7ALRSIeWcLoGxTA3vKg9GRRBlef0aZxelVygcJW1-ygwi-NhZLAN2eZlwv4_prnS_6dIix7YkDXAs5Nv1HU_c2vBhxpFU_l7VdablQ3sqgzBVw5uqMXI6wfNi-rZtI6GVTiXIfVHwkHTf0D5nH9wNgIH__4aKpyTYS4X6rQH3C9mwLnmbGi5TaHor7L46QEcccD8F8mI2EREbUYR7wiDD8fwqWO8hZ_jTyqOXU5m4Mn7540VGsmAlE-nx0I75wkxuVRui-wTH0zlh9dpJqqGMmt-Xqa-upOQI686-d39AlxLcnVOdmLWIBJCKoxTp9sQBaiZTMutJHIFnZ1KHjQjxEc0pjHMPsWxm3AmZ3GI__RzlTm38-QuPHD2sYfzzwzi8IC27ceeJxhBRlTCqs1xWR97HSr36NTM_rAL5sbh21K8kTWKodEADrESWwBtFAOvgx0l0dFkzH75a88mzlWNSWrKz8LG8EIrT4COwmohzRPOz6yvUZG3xPlir5lz3YWxHwmzdiP3AvdvDTaUYOHfQY-ZgtKoje147QSjCyF-sZrcfDiEtfmiZ6hfduu90

{
  "firstName": "Toi",
  "lastName": "La Huong",
  "phoneNumber": "0357654619",
  "address": "Ha Noi"
}