@url_dev=http://localhost:3000/api/v1/admin


### change-admin
POST {{url_dev}}/check-admin
Content-Type: application/json
X-Client-ID: 642fdcb4af2a0df12e662315
X-Device-ID: 642fdcb5af2a0df12e662318
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDJmZGNiNGFmMmEwZGYxMmU2NjIzMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjgwODYzMjkzLCJleHAiOjE2ODA4NjY4OTN9.cA1mUUqWPOi48M4J9qabPIgf2faNtd6rdVrYc-h5J0UWcx9y5dQRbvOTPyPGP5nvq9pl-I_KWzw7eiTzUTe2LlzabMaGzw89y_GLLTbI3rH-l2kG3pnDw-hlCF3j64JblI24jKHg9QwC_CcrrLwESlsnvUHXJSWkS5LD_dQ7axrIsoHHhPbT6V371BU6i18cH1SgdQACfkE7iAslMhUY0sWBV02LWb95FNMxClVxEBuHQo0YwQL-QFKO1d0s-KmUOM77Sk1_UozqjS00KT0TVK1fasMU_vi5kp50KHbK3NNtAfpRbKyQHAYjvtwE3Fdj5jXJmh-PW7zIHLXQUDxHFj4tlF1U3JP-EruU070hUw3mVtH1IuLt6wrTYNRgX06DW-xdU-qc3I3Wi0TyM_dz-op2rsSw6NsgtOuC4a3cjftXkvvQrnDpoeCb0q3ce4O6jwbZr-GnBflIyGQTuxX0CXCy-W-RUQ3ibvTiJfwtNw7pLquHWh-TLb0BQ-BpXESloz00EZUO4FYSI0XNHGjlJCJPIf6DPXPifgq2VGs0jdgDfGBZDFY0FoIz2fC72Rg6W7iPCx6EH5GmeZMMJUWAB5x0qVwNXspg9xuOFKLgqaw_zsaJ9Sgpd1wPLQJ45fMLCSI3sMhibUnggbnOzBKpga1Sp3CYQSXHOgsJ72FwalM
