@url_dev=http://localhost:3000/api/v1/roles


### create role
POST {{url_dev}}
Content-Type: application/json
X-Client-ID: 642fdcb4af2a0df12e662315
X-Device-ID: 642fdcb5af2a0df12e662318
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDJmZGNiNGFmMmEwZGYxMmU2NjIzMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjgwODk2MzMwLCJleHAiOjE2ODE1MDExMzB9.kx-iZTlabvV_hkNOHtx2Yr5iLaazfoFdi0oWmfS02-5cqUdwzZaurMk0nkgAQC9gK4QAGMXVg4agrQrhKLJLsOtRjXg-SHR1RuU5Bi2rS6EPMFcma1kMURLEEAbp_S4PvgrT2-1VK9vH2LWfuJmKgqCeIYsrrficFpo4e0LyJmARGjM0luu_HJEg48MYWeZmrWcLUtWUaCcH4XE14SUScrhp3cdVYIa3ptEyhJllHZXMhA0B-x7o52t8vZPGKmedoZsP4PbzPeKjpQ0MUtnWJppBNEtN0QHXFQZ1ehCaovxUdkiJkSxScbtmm6MQXnnX6pIJ26kUX4r4b-cm5il8e-vX2zNLFkDPnmGHx_EAGKJGeYYyCzCXULyZEvziCIs6nFfIntgiFQgpv4YkFT8NMaRfyNqTbv1cCPQyOMr96nm_Je7NfrvEQe_Q6DeHws0_DThCW2P3bAvTu5VLhsaUNxefL22Nci-EBiRHwA_AA7Pgtli65L_ts3MkYQIx6bTwx3HbZCyte4gBEZAvEJ6WeMocGWyxrb-xHlR6IvzrPu4PRADcIILl1tGaOI96N_Ypn0Bqzqw5jFgf98wUNLvLF4xHHoCYVXRxFtiIw82KzHLTliy1R9_sVTDyd8Z9zWvbN904-YKciRLXjU9_NklP8RosD-0JGOdYXpDdgHJ4xU4

{
  "name": "abcde",
  "scopes": ["test"]
}



### update role
PUT {{url_dev}}/6430718a0eb7d0aa78083d98
Content-Type: application/json
X-Client-ID: 642fdcb4af2a0df12e662315
X-Device-ID: 642fdcb5af2a0df12e662318
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDJmZGNiNGFmMmEwZGYxMmU2NjIzMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjgwODk2MzMwLCJleHAiOjE2ODE1MDExMzB9.kx-iZTlabvV_hkNOHtx2Yr5iLaazfoFdi0oWmfS02-5cqUdwzZaurMk0nkgAQC9gK4QAGMXVg4agrQrhKLJLsOtRjXg-SHR1RuU5Bi2rS6EPMFcma1kMURLEEAbp_S4PvgrT2-1VK9vH2LWfuJmKgqCeIYsrrficFpo4e0LyJmARGjM0luu_HJEg48MYWeZmrWcLUtWUaCcH4XE14SUScrhp3cdVYIa3ptEyhJllHZXMhA0B-x7o52t8vZPGKmedoZsP4PbzPeKjpQ0MUtnWJppBNEtN0QHXFQZ1ehCaovxUdkiJkSxScbtmm6MQXnnX6pIJ26kUX4r4b-cm5il8e-vX2zNLFkDPnmGHx_EAGKJGeYYyCzCXULyZEvziCIs6nFfIntgiFQgpv4YkFT8NMaRfyNqTbv1cCPQyOMr96nm_Je7NfrvEQe_Q6DeHws0_DThCW2P3bAvTu5VLhsaUNxefL22Nci-EBiRHwA_AA7Pgtli65L_ts3MkYQIx6bTwx3HbZCyte4gBEZAvEJ6WeMocGWyxrb-xHlR6IvzrPu4PRADcIILl1tGaOI96N_Ypn0Bqzqw5jFgf98wUNLvLF4xHHoCYVXRxFtiIw82KzHLTliy1R9_sVTDyd8Z9zWvbN904-YKciRLXjU9_NklP8RosD-0JGOdYXpDdgHJ4xU4

{
  "name": "abcde",
  "scopes": ["test", "789"]
}

### update role
DELETE {{url_dev}}/6430718a0eb7d0aa78083d98
Content-Type: application/json
X-Client-ID: 642fdcb4af2a0df12e662315
X-Device-ID: 642fdcb5af2a0df12e662318
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDJmZGNiNGFmMmEwZGYxMmU2NjIzMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjgwODk2MzMwLCJleHAiOjE2ODE1MDExMzB9.kx-iZTlabvV_hkNOHtx2Yr5iLaazfoFdi0oWmfS02-5cqUdwzZaurMk0nkgAQC9gK4QAGMXVg4agrQrhKLJLsOtRjXg-SHR1RuU5Bi2rS6EPMFcma1kMURLEEAbp_S4PvgrT2-1VK9vH2LWfuJmKgqCeIYsrrficFpo4e0LyJmARGjM0luu_HJEg48MYWeZmrWcLUtWUaCcH4XE14SUScrhp3cdVYIa3ptEyhJllHZXMhA0B-x7o52t8vZPGKmedoZsP4PbzPeKjpQ0MUtnWJppBNEtN0QHXFQZ1ehCaovxUdkiJkSxScbtmm6MQXnnX6pIJ26kUX4r4b-cm5il8e-vX2zNLFkDPnmGHx_EAGKJGeYYyCzCXULyZEvziCIs6nFfIntgiFQgpv4YkFT8NMaRfyNqTbv1cCPQyOMr96nm_Je7NfrvEQe_Q6DeHws0_DThCW2P3bAvTu5VLhsaUNxefL22Nci-EBiRHwA_AA7Pgtli65L_ts3MkYQIx6bTwx3HbZCyte4gBEZAvEJ6WeMocGWyxrb-xHlR6IvzrPu4PRADcIILl1tGaOI96N_Ypn0Bqzqw5jFgf98wUNLvLF4xHHoCYVXRxFtiIw82KzHLTliy1R9_sVTDyd8Z9zWvbN904-YKciRLXjU9_NklP8RosD-0JGOdYXpDdgHJ4xU4
